/***************************************************************************
 *
 * Copyright (C) 2007 - 2012, Rogvall Invest AB, <tony@rogvall.se>
 *
 * This software is licensed as described in the file COPYRIGHT, which
 * you should have received as part of this distribution. The terms
 * are also available at http://www.rogvall.se/docs/copyright.txt.
 *
 * You may opt to use, copy, modify, merge, publish, distribute and/or sell
 * copies of the Software, and permit persons to whom the Software is
 * furnished to do so, under the terms of the COPYRIGHT file.
 *
 * This software is distributed on an "AS IS" basis, WITHOUT WARRANTY OF ANY
 * KIND, either express or implied.
 *
 ***************************************************************************/
/*
 *  Definition HTML named colors
 */
#ifndef __EPX_COLORS__
#define __EPX_COLORS__

#include "epx_pixel.h"

#define epx_pixel_aliceBlue     epx_pixel_rgb(0xF0,0xF8,0xFF)	 
#define epx_pixel_antiqueWhite  epx_pixel_rgb(0xFA,0xEB,0xD7)	 
#define epx_pixel_aqua 	     epx_pixel_rgb(0x00,0xFF,0xFF)	 
#define epx_pixel_aquamarine    epx_pixel_rgb(0x7F,0xFF,0xD4)	 
#define epx_pixel_azure 	     epx_pixel_rgb(0xF0,0xFF,0xFF)	 
#define epx_pixel_beige 	     epx_pixel_rgb(0xF5,0xF5,0xDC)	 
#define epx_pixel_bisque 	     epx_pixel_rgb(0xFF,0xE4,0xC4)	 
#define epx_pixel_black 	     epx_pixel_rgb(0x00,0x00,0x00)	 
#define epx_pixel_blanchedAlmond 	epx_pixel_rgb(0xFF,0xEB,0xCD)	 
#define epx_pixel_blue 	        epx_pixel_rgb(0x00,0x00,0xFF)	 
#define epx_pixel_blueViolet 	epx_pixel_rgb(0x8A,0x2B,0xE2)	 
#define epx_pixel_brown 	        epx_pixel_rgb(0xA5,0x2A,0x2A)	 
#define epx_pixel_burlyWood 	epx_pixel_rgb(0xDE,0xB8,0x87)	 
#define epx_pixel_cadetBlue 	epx_pixel_rgb(0x5F,0x9E,0xA0)	 
#define epx_pixel_chartreuse 	epx_pixel_rgb(0x7F,0xFF,0x00)	 
#define epx_pixel_chocolate 	epx_pixel_rgb(0xD2,0x69,0x1E)	 
#define epx_pixel_coral 	epx_pixel_rgb(0xFF,0x7F,0x50)	 
#define epx_pixel_cornflowerBlue 	epx_pixel_rgb(0x64,0x95,0xED)	 
#define epx_pixel_cornsilk 	epx_pixel_rgb(0xFF,0xF8,0xDC)	 
#define epx_pixel_crimson 	epx_pixel_rgb(0xDC,0x14,0x3C)	 
#define epx_pixel_cyan 	epx_pixel_rgb(0x00,0xFF,0xFF)	 
#define epx_pixel_darkBlue 	epx_pixel_rgb(0x00,0x00,0x8B)	 
#define epx_pixel_darkCyan 	epx_pixel_rgb(0x00,0x8B,0x8B)	 
#define epx_pixel_darkGoldenRod 	epx_pixel_rgb(0xB8,0x86,0x0B)	 
#define epx_pixel_darkGray 	epx_pixel_rgb(0xA9,0xA9,0xA9)	 
#define epx_pixel_darkGrey 	epx_pixel_rgb(0xA9,0xA9,0xA9)	 
#define epx_pixel_darkGreen 	epx_pixel_rgb(0x00,0x64,0x00)	 
#define epx_pixel_darkKhaki 	epx_pixel_rgb(0xBD,0xB7,0x6B)	 
#define epx_pixel_darkMagenta 	epx_pixel_rgb(0x8B,0x00,0x8B)	 
#define epx_pixel_darkOliveGreen 	epx_pixel_rgb(0x55,0x6B,0x2F)	 
#define epx_pixel_darkorange 	epx_pixel_rgb(0xFF,0x8C,0x00)	 
#define epx_pixel_darkOrchid 	epx_pixel_rgb(0x99,0x32,0xCC)	 
#define epx_pixel_darkRed 	epx_pixel_rgb(0x8B,0x00,0x00)	 
#define epx_pixel_darkSalmon 	epx_pixel_rgb(0xE9,0x96,0x7A)	 
#define epx_pixel_darkSeaGreen 	epx_pixel_rgb(0x8F,0xBC,0x8F)	 
#define epx_pixel_darkSlateBlue 	epx_pixel_rgb(0x48,0x3D,0x8B)	 
#define epx_pixel_darkSlateGray 	epx_pixel_rgb(0x2F,0x4F,0x4F)	 
#define epx_pixel_darkSlateGrey 	epx_pixel_rgb(0x2F,0x4F,0x4F)	 
#define epx_pixel_darkTurquoise 	epx_pixel_rgb(0x00,0xCE,0xD1)	 
#define epx_pixel_darkViolet 	epx_pixel_rgb(0x94,0x00,0xD3)	 
#define epx_pixel_deepPink 	epx_pixel_rgb(0xFF,0x14,0x93)	 
#define epx_pixel_deepSkyBlue 	epx_pixel_rgb(0x00,0xBF,0xFF)	 
#define epx_pixel_dimGray 	epx_pixel_rgb(0x69,0x69,0x69)	 
#define epx_pixel_dimGrey 	epx_pixel_rgb(0x69,0x69,0x69)	 
#define epx_pixel_dodgerBlue 	epx_pixel_rgb(0x1E,0x90,0xFF)	 
#define epx_pixel_fireBrick 	epx_pixel_rgb(0xB2,0x22,0x22)	 
#define epx_pixel_floralWhite 	epx_pixel_rgb(0xFF,0xFA,0xF0)	 
#define epx_pixel_forestGreen 	epx_pixel_rgb(0x22,0x8B,0x22)	 
#define epx_pixel_fuchsia 	epx_pixel_rgb(0xFF,0x00,0xFF)	 
#define epx_pixel_gainsboro 	epx_pixel_rgb(0xDC,0xDC,0xDC)	 
#define epx_pixel_ghostWhite 	epx_pixel_rgb(0xF8,0xF8,0xFF)	 
#define epx_pixel_gold 	epx_pixel_rgb(0xFF,0xD7,0x00)	 
#define epx_pixel_goldenRod 	epx_pixel_rgb(0xDA,0xA5,0x20)	 
#define epx_pixel_gray 	epx_pixel_rgb(0x80,0x80,0x80)	 
#define epx_pixel_grey 	epx_pixel_rgb(0x80,0x80,0x80)	 
#define epx_pixel_green 	epx_pixel_rgb(0x00,0x80,0x00)	 
#define epx_pixel_greenYellow 	epx_pixel_rgb(0xAD,0xFF,0x2F)	 
#define epx_pixel_honeyDew 	epx_pixel_rgb(0xF0,0xFF,0xF0)	 
#define epx_pixel_hotPink 	epx_pixel_rgb(0xFF,0x69,0xB4)	 
#define epx_pixel_indianRed  	epx_pixel_rgb(0xCD,0x5C,0x5C)	 
#define epx_pixel_indigo  	epx_pixel_rgb(0x4B,0x00,0x82)	 
#define epx_pixel_ivory 	epx_pixel_rgb(0xFF,0xFF,0xF0)	 
#define epx_pixel_khaki 	epx_pixel_rgb(0xF0,0xE6,0x8C)	 
#define epx_pixel_lavender 	epx_pixel_rgb(0xE6,0xE6,0xFA)	 
#define epx_pixel_lavenderBlush 	epx_pixel_rgb(0xFF,0xF0,0xF5)	 
#define epx_pixel_lawnGreen 	epx_pixel_rgb(0x7C,0xFC,0x00)	 
#define epx_pixel_lemonChiffon 	epx_pixel_rgb(0xFF,0xFA,0xCD)	 
#define epx_pixel_lightBlue 	epx_pixel_rgb(0xAD,0xD8,0xE6)	 
#define epx_pixel_lightCoral 	epx_pixel_rgb(0xF0,0x80,0x80)	 
#define epx_pixel_lightCyan 	epx_pixel_rgb(0xE0,0xFF,0xFF)	 
#define epx_pixel_lightGoldenRodYellow 	epx_pixel_rgb(0xFA,0xFA,0xD2)	 
#define epx_pixel_lightGray 	epx_pixel_rgb(0xD3,0xD3,0xD3)	 
#define epx_pixel_lightGrey 	epx_pixel_rgb(0xD3,0xD3,0xD3)	 
#define epx_pixel_lightGreen 	epx_pixel_rgb(0x90,0xEE,0x90)	 
#define epx_pixel_lightPink 	epx_pixel_rgb(0xFF,0xB6,0xC1)	 
#define epx_pixel_lightSalmon 	epx_pixel_rgb(0xFF,0xA0,0x7A)	 
#define epx_pixel_lightSeaGreen 	epx_pixel_rgb(0x20,0xB2,0xAA)	 
#define epx_pixel_lightSkyBlue 	epx_pixel_rgb(0x87,0xCE,0xFA)	 
#define epx_pixel_lightSlateGray 	epx_pixel_rgb(0x77,0x88,0x99)	 
#define epx_pixel_lightSlateGrey 	epx_pixel_rgb(0x77,0x88,0x99)	 
#define epx_pixel_lightSteelBlue 	epx_pixel_rgb(0xB0,0xC4,0xDE)	 
#define epx_pixel_lightYellow 	epx_pixel_rgb(0xFF,0xFF,0xE0)	 
#define epx_pixel_lime 	epx_pixel_rgb(0x00,0xFF,0x00)	 
#define epx_pixel_limeGreen 	epx_pixel_rgb(0x32,0xCD,0x32)	 
#define epx_pixel_linen 	epx_pixel_rgb(0xFA,0xF0,0xE6)	 
#define epx_pixel_magenta 	epx_pixel_rgb(0xFF,0x00,0xFF)	 
#define epx_pixel_maroon 	epx_pixel_rgb(0x80,0x00,0x00)	 
#define epx_pixel_mediumAquaMarine 	epx_pixel_rgb(0x66,0xCD,0xAA)	 
#define epx_pixel_mediumBlue 	epx_pixel_rgb(0x00,0x00,0xCD)	 
#define epx_pixel_mediumOrchid 	epx_pixel_rgb(0xBA,0x55,0xD3)	 
#define epx_pixel_mediumPurple 	epx_pixel_rgb(0x93,0x70,0xD8)	 
#define epx_pixel_mediumSeaGreen 	epx_pixel_rgb(0x3C,0xB3,0x71)	 
#define epx_pixel_mediumSlateBlue 	epx_pixel_rgb(0x7B,0x68,0xEE)	 
#define epx_pixel_mediumSpringGreen 	epx_pixel_rgb(0x00,0xFA,0x9A)	 
#define epx_pixel_mediumTurquoise 	epx_pixel_rgb(0x48,0xD1,0xCC)	 
#define epx_pixel_mediumVioletRed 	epx_pixel_rgb(0xC7,0x15,0x85)	 
#define epx_pixel_midnightBlue 	epx_pixel_rgb(0x19,0x19,0x70)	 
#define epx_pixel_mintCream 	epx_pixel_rgb(0xF5,0xFF,0xFA)	 
#define epx_pixel_mistyRose 	epx_pixel_rgb(0xFF,0xE4,0xE1)	 
#define epx_pixel_moccasin 	epx_pixel_rgb(0xFF,0xE4,0xB5)	 
#define epx_pixel_navajoWhite 	epx_pixel_rgb(0xFF,0xDE,0xAD)	 
#define epx_pixel_navy 	epx_pixel_rgb(0x00,0x00,0x80)	 
#define epx_pixel_oldLace 	epx_pixel_rgb(0xFD,0xF5,0xE6)	 
#define epx_pixel_olive 	epx_pixel_rgb(0x80,0x80,0x00)	 
#define epx_pixel_oliveDrab 	epx_pixel_rgb(0x6B,0x8E,0x23)	 
#define epx_pixel_orange 	epx_pixel_rgb(0xFF,0xA5,0x00)	 
#define epx_pixel_orangeRed 	epx_pixel_rgb(0xFF,0x45,0x00)	 
#define epx_pixel_orchid 	epx_pixel_rgb(0xDA,0x70,0xD6)	 
#define epx_pixel_paleGoldenRod 	epx_pixel_rgb(0xEE,0xE8,0xAA)	 
#define epx_pixel_paleGreen 	epx_pixel_rgb(0x98,0xFB,0x98)	 
#define epx_pixel_paleTurquoise 	epx_pixel_rgb(0xAF,0xEE,0xEE)	 
#define epx_pixel_paleVioletRed 	epx_pixel_rgb(0xD8,0x70,0x93)	 
#define epx_pixel_papayaWhip   epx_pixel_rgb(0xFF,0xEF,0xD5)	 
#define epx_pixel_peachPuff 	  epx_pixel_rgb(0xFF,0xDA,0xB9)	 
#define epx_pixel_peru 	  epx_pixel_rgb(0xCD,0x85,0x3F)	 
#define epx_pixel_pink 	  epx_pixel_rgb(0xFF,0xC0,0xCB)	 
#define epx_pixel_plum 	  epx_pixel_rgb(0xDD,0xA0,0xDD)	 
#define epx_pixel_powderBlue   epx_pixel_rgb(0xB0,0xE0,0xE6)	 
#define epx_pixel_purple 	  epx_pixel_rgb(0x80,0x00,0x80)	 
#define epx_pixel_red 	  epx_pixel_rgb(0xFF,0x00,0x00)	 
#define epx_pixel_rosyBrown 	  epx_pixel_rgb(0xBC,0x8F,0x8F)	 
#define epx_pixel_royalBlue 	  epx_pixel_rgb(0x41,0x69,0xE1)	 
#define epx_pixel_saddleBrown  epx_pixel_rgb(0x8B,0x45,0x13)	 
#define epx_pixel_salmon 	  epx_pixel_rgb(0xFA,0x80,0x72)	 
#define epx_pixel_sandyBrown   epx_pixel_rgb(0xF4,0xA4,0x60)	 
#define epx_pixel_seaGreen 	  epx_pixel_rgb(0x2E,0x8B,0x57)	 
#define epx_pixel_seaShell 	  epx_pixel_rgb(0xFF,0xF5,0xEE)	 
#define epx_pixel_sienna 	  epx_pixel_rgb(0xA0,0x52,0x2D)	 
#define epx_pixel_silver 	  epx_pixel_rgb(0xC0,0xC0,0xC0)	 
#define epx_pixel_skyBlue 	  epx_pixel_rgb(0x87,0xCE,0xEB)	 
#define epx_pixel_slateBlue 	  epx_pixel_rgb(0x6A,0x5A,0xCD)	 
#define epx_pixel_slateGray 	  epx_pixel_rgb(0x70,0x80,0x90)	 
#define epx_pixel_slateGrey 	  epx_pixel_rgb(0x70,0x80,0x90)	 
#define epx_pixel_snow 	  epx_pixel_rgb(0xFF,0xFA,0xFA)	 
#define epx_pixel_springGreen  epx_pixel_rgb(0x00,0xFF,0x7F)	 
#define epx_pixel_steelBlue 	  epx_pixel_rgb(0x46,0x82,0xB4)	 
#define epx_pixel_tan 	  epx_pixel_rgb(0xD2,0xB4,0x8C)	 
#define epx_pixel_teal 	  epx_pixel_rgb(0x00,0x80,0x80)	 
#define epx_pixel_thistle 	  epx_pixel_rgb(0xD8,0xBF,0xD8)	 
#define epx_pixel_tomato 	  epx_pixel_rgb(0xFF,0x63,0x47)	 
#define epx_pixel_turquoise 	  epx_pixel_rgb(0x40,0xE0,0xD0)	 
#define epx_pixel_violet 	  epx_pixel_rgb(0xEE,0x82,0xEE)	 
#define epx_pixel_wheat 	  epx_pixel_rgb(0xF5,0xDE,0xB3)	 
#define epx_pixel_white 	  epx_pixel_rgb(0xFF,0xFF,0xFF)	 
#define epx_pixel_whiteSmoke   epx_pixel_rgb(0xF5,0xF5,0xF5)	 
#define epx_pixel_yellow 	  epx_pixel_rgb(0xFF,0xFF,0x00)	 
#define epx_pixel_yellowGreen  epx_pixel_rgb(0x9A,0xCD,0x32)	 

#endif
